{
  "uid" : "5ffe0cf8c6fc19c0",
  "name" : "test_broken",
  "fullName" : "testcase.test_login.Testfour#test_broken",
  "historyId" : "30bb666e68d2c752af936ba2ac037f11",
  "time" : {
    "start" : 1652844302500,
    "stop" : 1652844302500,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "Exception: oops",
  "statusTrace" : "self = <testcase.test_login.Testfour object at 0x7f7dc26b3640>\n\n    def test_broken(self):\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_login.py:118: Exception",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "测试报告显示"
  }, {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "Testfour"
  }, {
    "name" : "host",
    "value" : "tangzhongkaideMacBook-Pro.local"
  }, {
    "name" : "thread",
    "value" : "49233-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "5ffe0cf8c6fc19c0.json",
  "parameterValues" : [ ]
}