{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "self = <testcase.test_login.Testfour object at 0x7f9436f46c20>\n\n    @allure.story(\"中断模块\")\n    def test_broken(self):\n>       raise Exception('oops')\nE       Exception: oops\n\ntestcase/test_login.py:124: Exception"}, "start": 1652845175424, "stop": 1652845175424, "uuid": "16e53a77-4605-4eff-96cc-6734503230b0", "historyId": "30bb666e68d2c752af936ba2ac037f11", "testCaseId": "01a100b4540167d6026ec96a476def21", "fullName": "testcase.test_login.Testfour#test_broken", "labels": [{"name": "feature", "value": "测试报告显示"}, {"name": "story", "value": "中断模块"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Testfour"}, {"name": "host", "value": "tangzhongkaideMacBook-Pro.local"}, {"name": "thread", "value": "56048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}